### ISSUE TITLE
Create a setup guide for first time users

### ISSUE THREAD

**Issue by SpookyTabz** [giawa/GiawaOS#1]
make a setup guide that will say what u need to have installed, so people dont need try out multiple extensions

**Comment by giawa** [comment]
Hi there, thanks for the comment!  I've extended the README to include a `Getting Started` section.  Does that help clear things up?

**Comment by giawa** [comment]
Closing this for now as I am hopeful the issue is resolve.  Feel free to open it again if you have any questions.  Thanks!
